export const sample_foods = [
    {
        F_id: '1',
        F_name: 'Pizza Pepperoni',
        F_cookTime: "10-20",
        F_price: 1500.00,
        F_favourite: false,
        F_origins: ['italy'],
        F_stars: 4.5,
        F_imageUrl: 'food-1.jpg',
        F_tags: ['FastFood', 'Pizza', 'Lunch'],
    },

    {
        F_id: '2',
        F_name: 'Meatball',
        F_price: 675.00,
        F_cookTime: "20-30",
        F_favourite: true,
        F_origins: ['persia', 'middle east', 'china'],
        F_stars: 5,
        F_imageUrl: 'food-2.jpg',
        F_tags: ['SlowFood', 'Lunch'],
    },

    {
        F_id: '3',
        F_name: 'Hamburger',
        F_price: 350.00,
        F_cookTime: "10-15",
        F_favourite: false,
        F_origins: ['germany', 'us'],
        F_stars: 3.5,
        F_imageUrl: 'food-3.jpg',
        F_tags: ['FastFood', 'Hamburger'],
    },

    {
        F_id: '4',
        F_name: 'Fried Potatoes',
        F_price: 300.00,
        F_cookTime: "15-20",
        F_favourite: true,
        F_origins: ['belgium', 'france'],
        F_stars: 3,
        F_imageUrl: 'food-4.jpg',
        F_tags: ['FastFood', 'Fry', 'Potatoes'],
    },

    {
        F_id: '5',
        F_name: 'Chicken Soup',
        F_price: 700.00,
        F_cookTime: "40-50",
        F_favourite: false,
        F_origins: ['india', 'asia'],
        F_stars: 3.5,
        F_imageUrl: 'food-5.jpg',
        F_tags: ['SlowFood', 'Soup'],
    },

    {
        F_id: '6',
        F_name: 'Vegetables Pizza',
        F_price: 1200.00,
        F_cookTime: "30-45",
        F_favourite: false,
        F_origins: ['italy'],
        F_stars: 4.0,
        F_imageUrl: 'food-6.jpg',
        F_tags: ['FastFood', 'Pizza', 'Lunch'],
    },

    {
        F_id: '7',
        F_name: 'Chicken Kottu',
        F_price: 1050.00,
        F_cookTime: "20-30",
        F_favourite: true,
        F_origins: ['srilanka', 'india'],
        F_stars: 4.5,
        F_imageUrl: 'food-7.jpg',
        F_tags: ['SlowFood', 'Kottu', 'Lunch'],
    },

    {
        F_id: '8',
        F_name: 'Noodles',
        F_price: 950.00,
        F_cookTime: "20-25",
        F_favourite: false,
        F_origins: ['china', 'middle east'],
        F_stars: 2.5,
        F_imageUrl: 'food-8.jpg',
        F_tags: ['SlowFood', 'Noodles', 'Lunch'],
    },

    {
        F_id: '9',
        F_name: 'Pasta',
        F_price: 750.00,
        F_cookTime: "20-25",
        F_favourite: true,
        F_origins: ['italy'],
        F_stars: 3.0,
        F_imageUrl: 'food-9.jpg',
        F_tags: ['SlowFood', 'Pasta', 'Dinner'],
    },

    {
        F_id: '10',
        F_name: 'Fried Rice',
        F_price: 1100.00,
        F_cookTime: "35-45",
        F_favourite: false,
        F_origins: ['china'],
        F_stars: 4.0,
        F_imageUrl: 'food-10.jpg',
        F_tags: ['SlowFood', 'Rice', 'Dinner'],
    }
];

export const sample_tags = [
    { name: 'All', count: 10},
    { name: 'FastFood', count: 4},
    { name: 'Pizza', count: 2},
    { name: 'Lunch', count: 5},
    { name: 'SlowFood', count: 6},
    { name: 'Hamburger', count: 1},
    { name: 'Fry', count: 1},
    { name: 'Soup', count: 1},
];